rename	3rdPartyConnector.pdf	Altibase_3rd_Party_Connector_Guide.pdf
rename	ACI.pdf	Altibase_C_Interface_Manual.pdf
rename	Admin_1.pdf	Administrator's_Manual1.pdf
rename	Admin_2.pdf	Administrator's_Manual2.pdf
rename	API.pdf	Application_Program_Interface_User's_Manual.pdf
rename	CLI_1.pdf	CLI_User's_Manual1.pdf
rename	CLI_2.pdf	CLI_User's_Manual2.pdf
rename	DBLink.pdf	DB_Link_User's_Manual.pdf
rename	ErrorMessage.pdf	Error_Message_Reference.pdf
rename	ExternalProcedure.pdf	External_Procedures_Manual.pdf
rename	GeneralReference_1.pdf	General_Reference1.pdf
rename	GeneralReference_2.pdf	General_Reference2.pdf
rename	GeneralReference_3.pdf	General_Reference3.pdf
rename	GeneralReference_4.pdf	General_Reference4.pdf
rename	GettingStarted.pdf	Getting_Started_Guide.pdf
rename	HadoopConnector.pdf	Hadoop_Connector_User's_Manual.pdf
rename	Heartbeat.pdf	Altibase_Heartbeat_User's_Guide.pdf
rename	iLoader.pdf	iLoader_User's_Manual.pdf
rename	Installation.pdf	Installation_Guide.pdf
rename	iSQL.pdf	iSQL_User's_Manual.pdf
rename	JDBC.pdf	JDBC_User's_Manual.pdf
rename	JdbcAdapter.pdf	Adapter_for_JDBC_User's_Manual.pdf
rename	LogAnalyzer.pdf	Log_Analyzer_User's_Manual.pdf
rename	MigrationCenter.pdf	Migration_Center_User's_Manual.pdf
rename	MonitorAPI.pdf	Monitoring_API_Developer's_Guide.pdf
rename	NewFeaturesGuide.pdf	New_Features_Guide.pdf
rename	ODBCDriver.pdf	ODBC_User's_Manual.pdf
rename	OraAdapter.pdf	Adapter_for_Oracle_User's_Manual.pdf
rename	Precompiler_1.pdf	Precompiler_User's_Manual1.pdf
rename	Precompiler_2.pdf	Precompiler_User's_Manual2.pdf
rename	Replication.pdf	Replication Manual.pdf
rename	ReplicationManager.pdf	Replication_Manager_User's_Manual.pdf
rename	Sharding.pdf	Altibase_Sharding_Guide.pdf
rename	SNMP.pdf	SNMP_Agent_Guide.pdf
rename	SpatialSQL.pdf	Spatial_SQL_Reference.pdf
rename	SQL1.pdf	SQL_Reference1.pdf
rename	SQL2.pdf	SQL_Reference2.pdf
rename	SQL3.pdf	SQL_Reference3.pdf
rename	SQL4.pdf	SQL_Reference4.pdf
rename	SSL.pdf	Altibase_SSL_TLS_User's_Guide.pdf
rename	StoredProcedure1.pdf	Stored_Procedures_Manual1.pdf
rename	StoredProcedure2.pdf	Stored_Procedures_Manual2.pdf
rename	TuningGuide.pdf	Performance_Tuning_Guide.pdf
rename	Utilities.pdf	Utilities_Manual.pdf
